name: Build OxidOS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: oxid-os

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview

      - name: Install bootimage
        run: cargo install bootimage

      - name: Add custom target
        run: rustup target add x86_64-unknown-none

      - name: Install QEMU
        run: sudo apt-get update && sudo apt-get install -y qemu-system-x86

      - name: Build
        run: cargo bootimage --target x86_64-oxid_os.json
